---
title: "Exercise_final (Chapter4-6)"
author: "TerrenceN"
date: "September 13, 2019"
output: html_document
---

## Exercise 4.1
```{r}
ter <- c(6,9,7,3,6,7,9,6,3,6,6,7,1,9,1) 
ter
ter==6
ter >= 6
ter<6+2
ter !=6

terb <-c (3,6,7,9,6,3,6,6,7,1,9,1)
terb
terc <- array(data=c(terb),dim =c(2,2,3))
terc

terc <= (6/2)+4
terd <- c(terc)+2
terd <= 6

AQ <- diag(x=10)
AQ
AQ == 0

terc == T

AZ <- diag(AQ)
AZ
AZ != T

```
## Exercise 4.2
```{r}
foo <- c(7,1,7,10,5,9,10,3,10,8)
foo
foor <- foo > 5| foo == 2
foor

bar <- c(8,8,4,4,5,1,5,6,6,8)
bar
barr <- bar<=6 & bar != 4
barr

zoo <- foor & barr
zoo

baz <- c(foo + bar)
baz
baaz <- c(baz <= 14) | c(baz !=15)
baaz
baaw <- ((baz/foo) > 4 | (baz/foo) <= 2)
baaw

```
## Exercise 4.3
```{r}
foo <- c(7,5,6,1,2,10,8,3,8,2)
foo

bar <- foo[foo>= 5]
bar

foo2 <-  foo[(foo< 5)]
foo2

bez <- matrix(data=c(bar),nrow=2,ncol=3)
bez
sq<- (bez[1,2])^2
sq

bez <- c(bez)
bez
bez [c(5,6)] <- c(sq,sq)
bez

bez[(bez<=25)&(bez > 4)]
bez

qq <- c(10,5,1,4,7,4,3,3,1,3,4,3,1,7,8,3,7,3)
qq
qux <- array(qq,dim=c(3,2,3))
qux

which((x=qux ==3)| (x=qux ==4),arr.ind =T)
qux
qux<- qux[(qux <3) ||(qux >= 7)] <- 100 
qux
```
## Exercise 4.4
```{r}
cat("The quick brown fox\n\tjumped over\n\t\tthe lazy dogs")
num1 <- 4
num1
num2 <- 0.75
num2
paste("The result of multipying ",num1,"by",num2,"is",num1*num2)

loc <- c("/Users","/tdavies","/Documents","/RBook/")
loc
paste(loc[1],loc[3],loc[4],"tnemayire",sep="")
loc2 <- c("/tnemayire")
loc2
paste (loc[1],loc[3],loc2[1],loc[4],sep="")

bar <- c("How","much","wood","could","a","woodchuck","chuck")
bar
length(x=bar)
bar2 <- c("if")
bar2
newbar <- paste(bar2[1],bar[5],bar[6],bar[4],bar[7],bar[3])
newbar
gsub(pattern="wood",replacement="metal",x=newbar)

cost <- c("Two","6-packs","for","$12.99")
cost
costs <- paste(cost[1],cost[2],cost[3],cost[4])
costs
substr(x=costs,start=5,stop=10)

gsub(pattern="12.99",replacement="10.99",x=costs)
```
## Exercise 4.5
```{r}
names <- c(1:26)
names
length(x=names)
name <- matrix(data=c(names))
name
sf <- name[c(1,5,6,7,12,14,15,16,23,24,25)] <- c(0,0,0,0,0,0,0,0,0,0,0)
sf
sm <- name [c(2,3,4,8,9,10,11,13,17,18,19,20,21,22,26)] <- c(1,1,1,1,1,1,1,1,1,1,1,1,1,1,1)
sm
name
sex.num <- c(name)
sex.num
sex.num.fac <- factor(x=sex.num)
sex.num.fac
levels(x=sex.num.fac)
levels(x=sex.num.fac) <- c("Female","Male")
sex.num.fac

lp <- name [c(1,4,12,15,16,19,24,26)] <- c(30,30,30,30,30,30) ##30 to be relabelled to Labour##
lp
gp <- name [c(6,9,11,25)] <- c(40,40,40) ## 40 to be relabelled to Greens##
gp
oth <- name [c(10,20)] <- c(50,50) ##50 to be relabelle to Other##
oth
nat <- name [c(2,3,5,7,8,13,14,17,18,21)] <- c(60,60,60,60,60,60,60,60,60) ##60 to be relabelled to National
nat
mao <- name [c(22,23)] <- c(70,70) ##70 to be relabelled to Maori
mao
length(x=nat)
name
party.num <- c(name)
party.num
party.num.fac <- factor(x=party.num)
party.num.fac
levels(x=party.num.fac)
levels(x=party.num.fac) <- c("Labour","Greens","Other","National","Maori")
party.num.fac
sex.num.fac

party.char.fac <- factor(x=party.num.fac, ordered = TRUE)
party.char.fac
## No sense in ordering since indiviuals are grouped by party of choice not in any order
## R sees to say Labour, Greens, Other then Natonal based on individual listing from 1-20

party.males <- (party.num.fac[sex.num.fac=="Male"])  ## returns factor vector of parties for males only
party.males
sex.national <- (sex.num.fac[party.num.fac== "National"])
sex.national

party.num.fac ## after adding 6 more individuals, their party's and gender type
sex.num.fac ## after adding 6 more individuals, their party's and gender type

conflevel <- c(93, 55, 29, 100,52, 84, 56, 0, 33, 52, 35, 53, 55, 46, 40, 40, 56, 45, 64, 31, 10, 29, 40,
95, 18, 61)
conflevel
confbreak <- c(0,30,70,100) ## (0 to less 30 -low),(30 to less than 70- Moderate),(70 to equal to 100 -high)
confbreak
cut (x=conflevel,breaks = confbreak)
cut (x=conflevel,breaks = confbreak,right = F)
cut (x=conflevel,breaks = confbreak,right = F,include.lowest = T)
confname <- c("Low","Moderate","High")
confname
confidencelevels <- cut (x=conflevel,breaks = confbreak,right = F,include.lowest = T,labels = confname)
confidencelevels

conflevellabor <- (confidencelevels[party.num.fac== "Labour"])
conflevellabor

conflevelNational <- (confidencelevels[party.num.fac== "National"])
conflevelNational

#labour confidence is between Moderate-High, and Nationals confidence is Low to Moderate ##

```
## Exercise 5.1
```{r}
seqlist<- seq(from=-4,to=4,length= 20)
seqlist
seqvector<-matrix(c(F,T,T,T,F,T,T,F,F),nrow=3, ncol=3)
seqvector
chrvek<-c("don", "quixote")
chrvek
facvec<- factor(x=c("LOW","MED","LOW","MED","MED","HIGH"))
facvec
newlists <- list(seqlist,seqvector,chrvek,facvec)
newlists
newlists[[2]][2:1,2:3]
newlists[[3]][1]<-sub(pattern="don", replacement="Don",x=newlists[[3]][1])
newlists[[3]][2]<-sub(pattern="quixote", replacement="Quixote",x=newlists[[3]][2])
newlists[[3]]
cat("\"Windmills! ATTACK!\"\n"," ","", "-\\" ,newlists[[3]],"/-")
wxy <- newlists[[1]][L[[1]]>1]
wxy
which(x=newlists[[4]]=="MED")


newlist2 <- list(facs=newlists[[4]],nums=c(3,2.1,3.3,4,1.5,4.9),oldlist=newlist[1:3])
newlist2

biggerthree <- newlist2$facs[][newlist2$nums>= 3]
biggerthree

newlist2$flags <- rep(x=newlist2$oldlist[1][3], times=2)
newlist2$flags

newelements <- newlist$nums[][!newlist$flags]
newelements

newlist2$oldlist[[3]]<- "Don Quixote"

```
# Exercise 5.2

```{r}
funny<-c("High","Med","Low","High","Med","Med")
funny <-factor(x=funny,levels = c("Low","Med","High"))
funny
dframe<-data.frame(person=c("Stan","Fran","Steve","Roger","Hay","Klaus"),sex=factor(c("M","F","M","M","F","M")),funny)
dframe <- cbind(dframe, age=c(41,41,15,1600,21,60))
dframe <- dframe[c(1,4,2,3)]
dframe

mydata <- data.frame(person=c("Peter","Lois","Meg","Chris","Stewie","Brian"),age=c(42,40,17,14,1,7),sex=factor(c("M","F","F","M","M","M")),stringsAsFactors=FALSE,funny=factor(x=c("High","High","Low","Med","High","Med"),levels=c("Low","Med","High")))
mydataframe <- rbind(mydata,dframe)
mydataframe
mydataframe[mydataframe$sex=='F'&(mydataframe$funny=='Med'|mydataframe$funny=='High'),]
mydataframe[substr(mydataframe$person,start=1,stop=1)=='S',]

```
## Exercise 6.1

```{r}
foo <- c(13563,-14156,-14319,16981,12921,11979,9568,8833,-12968,8133)
foo[which(x=is.infinite(foo^75))]
foo[which(x=foo^75 != -Inf)]
foo
bar <-matrix(c(77875.40, 27551.45, 23764.,30,-36478.88,-35466.25, -73333.85, 36599.69 -70585.69,-39803.81, 55976.34, 76694.82,47032.00),nrow=3,ncol=4)
bar
which(x=is.nan(bar^65/Inf))
bar[is.nan(bar^67+Inf)==FALSE]
bar[bar^67!=-Inf]
bar[bar==-Inf | is.finite(bar^67)]
```
#Exercise 6.2

```{r}
foo <- c(4.3,2.2,NULL,2.4,NaN,3.3,3.1,NULL,3.4,NA)
length(foo) ## length is 8
which(x=is.na(x=foo)) ## interger 0, hence false
is.null(x=foo) ## false
is.na(x=foo[8])+4/NULL ## gives numberic zero

xyzlist <- list(c(7,7,NA,3,NA,1,1,5,NA))
names(xyzlist) <-'alpha'
is.null('xyzlists$beta')
xyzlist$beta = which(is.na(xyzlist$alpha))
xyzlist
``` 
#Exercise 6.3
```{r}
is.array(foo <- array(data=1:36,dim=c(3,3,4))) ##array class
is.vector(bar <- as.vector(foo)) ## vctor class
is.character(baz <- as.character(bar))
is.factor(qux <- as.factor(baz))
is.numeric(quux <- bar+c(-0.1,0.1))

foosum <- is.numeric(foo) + is.integer(foo)
foosum  
barsum<- is.numeric(bar) + is.integer(bar)
barsum
bazsum <- is.numeric(baz) + is.integer(baz)
bazsum
quxsum <- is.numeric(qux) + is.integer(qux)
quxsum
quuxsum <- is.numeric(quux) + is.integer(quux)
quuxsum

factor(x = c(foosum, barsum, bazsum, quxsum, quuxsum),levels = c(0, 1, 2))
as.numeric(c(foosum, barsum, bazsum, quxsum, quuxsum))

mymatrix <- matrix(seq(from=2,to=13),nrow=3,ncol=4)
as.character(mymatrix)

secondmatrix <- matrix(c(34,23,33,42,41,0,1,1,0,0,1,2,1,1,2),nrow=5,ncol=3)
secondmatrix  
dataframesecondmatrix <- as.data.frame(secondmatrix)
dataframesecondmatrix

as.logical(dataframesecondmatrix[,2]) 
as.factor(dataframesecondmatrix[,3])
```

